services:
  # Backend Web Service
  - type: web
    name: book-a-doctor-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false

  # Frontend Static Site
  - type: web
    name: book-a-doctor-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    rootDir: frontend
    envVars:
      - key: REACT_APP_API_URL
        sync: false
